In [1]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/machine_learning_utfpr/knn/iris.csv')
df.head()

,Id,SepalLength[cm],SepalWidth[cm],PetalLength[cm],PetalWidth[cm],Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa

In [2]:
d = {'Iris-setosa': 0,
     'Iris-versicolor': 1,
     'Iris-virginica': 2}

df['Species'] = df['Species'].map(d)
df.head()

,Id,SepalLength[cm],SepalWidth[cm],PetalLength[cm],PetalWidth[cm],Species
0,1,5.1,3.5,1.4,0.2,0
1,2,4.9,3.0,1.4,0.2,0
2,3,4.7,3.2,1.3,0.2,0
3,4,4.6,3.1,1.5,0.2,0
4,5,5.0,3.6,1.4,0.2,0

In [3]:
X = df.iloc[:, 1:5].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [4]:
y = df['Species'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=123, stratify=y)
np.bincount(y_train)

array([40, 40, 40])

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_std = scaler.transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std

array([[-0.15385273, -0.58123819,  0.20169198,  0.14079576],
       [-1.03903283,  0.34874292, -1.46947014, -1.31116056],
       [ 0.60487307, -1.74371458,  0.37457082,  0.14079576],
       [-0.53321563,  1.97620986, -1.18133874, -1.0471685 ],
       [-0.53321563,  1.5112193 , -1.2965913 , -1.31116056],
       [ 2.37523326, -1.04622875,  1.81522782,  1.46075606],
       [-0.53321563,  0.81373347, -1.2965913 , -1.0471685 ],
       [-1.03903283,  1.27872403, -1.35421758, -1.31116056],
       [ 1.11069026,  0.58123819,  1.12371246,  1.196764  ],
       [ 1.49005316,  0.34874292,  0.54744966,  0.27279179],
       [-1.54485003,  0.81373347, -1.35421758, -1.17916453],
       [-0.91257853,  1.74371458, -1.06608618, -1.0471685 ],
       [-1.03903283,  0.81373347, -1.2965913 , -1.31116056],
       [ 1.74296176, -0.11624764,  1.18133874,  0.53678385],
       [-1.29194143,  0.81373347, -1.06608618, -1.31116056],
       [ 0.47841877,  0.81373347,  0.95083362,  1.46075606],
       [-1.16548713,  0.11624764, -1.2965913 , -1.44315659],
       [ 0.60487307,  0.58123819,  1.2965913 ,  1.72474812],
       [ 0.22551017, -0.34874292,  0.4321971 ,  0.40478782],
       [-1.29194143,  0.81373347, -1.23896502, -1.31116056],
       [-0.78612423,  2.44120041, -1.2965913 , -1.44315659],
       [ 0.85778167, -0.58123819,  0.48982338,  0.40478782],
       [ 0.73132737, -0.81373347,  0.89320734,  0.93277194],
       [ 0.47841877, -0.58123819,  0.60507594,  0.80077591],
       [-0.40676133, -1.04622875,  0.37457082,  0.00879974],
       [ 0.47841877, -0.34874292,  0.31694454,  0.14079576],
       [-0.53321563,  1.97620986, -1.41184386, -1.0471685 ],
       [ 0.85778167, -0.11624764,  1.18133874,  1.32876003],
       [-0.40676133, -1.27872403,  0.1440657 ,  0.14079576],
       [ 0.60487307, -0.58123819,  0.77795478,  0.40478782],
       [ 0.98423596, -0.34874292,  0.48982338,  0.14079576],
       [ 1.99587036, -0.58123819,  1.35421758,  0.93277194],
       [ 1.74296176,  1.27872403,  1.35421758,  1.72474812],
       [-0.15385273, -1.04622875, -0.1440657 , -0.25519232],
       [-1.03903283,  1.04622875, -1.41184386, -1.17916453],
       [ 1.23714456,  0.34874292,  1.23896502,  1.46075606],
       [ 0.22551017, -1.97620986,  0.7203285 ,  0.40478782],
       [-0.02739843, -0.81373347,  0.08643942,  0.00879974],
       [-0.02739843, -0.58123819,  0.77795478,  1.59275209],
       [-0.28030703, -0.11624764,  0.4321971 ,  0.40478782],
       [-0.40676133,  1.04622875, -1.41184386, -1.31116056],
       [-1.41839573,  0.34874292, -1.23896502, -1.31116056],
       [ 0.09905587, -0.11624764,  0.77795478,  0.80077591],
       [ 0.73132737,  0.11624764,  1.0084599 ,  0.80077591],
       [ 0.60487307, -0.34874292,  1.06608618,  0.80077591],
       [ 1.61650746, -0.11624764,  1.23896502,  1.196764  ],
       [-0.15385273,  3.13868625, -1.2965913 , -1.0471685 ],
       [-0.91257853, -1.27872403, -0.4321971 , -0.12319629],
       [-0.91257853,  0.81373347, -1.2965913 , -1.31116056],
       [-1.03903283,  1.04622875, -1.23896502, -0.78317644],
       [ 0.73132737,  0.34874292,  0.4321971 ,  0.40478782],
       [ 2.37523326, -0.58123819,  1.69997526,  1.06476797],
       [ 1.36359886,  0.11624764,  0.77795478,  1.46075606],
       [-0.02739843, -0.81373347,  0.20169198, -0.25519232],
       [ 0.09905587,  0.34874292,  0.60507594,  0.80077591],
       [-1.16548713,  0.11624764, -1.2965913 , -1.44315659],
       [ 0.73132737, -0.58123819,  1.06608618,  1.32876003],
       [-0.15385273, -1.27872403,  0.7203285 ,  1.06476797],
       [-0.91257853,  0.58123819, -1.18133874, -0.91517247],
       [ 0.73132737, -0.34874292,  0.31694454,  0.14079576],
       [-1.16548713, -0.11624764, -1.35421758, -1.31116056],
       [-0.28030703, -1.27872403,  0.08643942, -0.12319629],
       [-0.53321563, -0.11624764,  0.4321971 ,  0.40478782],
       [-0.91257853,  1.04622875, -1.35421758, -1.31116056],
       [-0.02739843,  2.20870514, -1.46947014, -1.31116056],
       [-1.79775862, -0.34874292, -1.35421758, -1.31116056],
       [-0.28030703, -0.81373347,  0.25931826,  0.14079576],
       [ 0.35196447, -1.04622875,  1.06608618,  0.27279179],
       [-0.15385273,  1.74371458, -1.18133874, -1.17916453],
       [ 1.86941606, -0.34874292,  1.46947014,  0.80077591],
       [-0.28030703, -0.11624764,  0.20169198,  0.14079576],
       [-0.28030703, -0.34874292, -0.08643942,  0.14079576],
       [ 1.11069026,  0.11624764,  1.06608618,  1.59275209],
       [ 0.60487307,  0.81373347,  1.06608618,  1.59275209],
       [-1.54485003,  0.11624764, -1.2965913 , -1.31116056],
       [ 0.73132737,  0.34874292,  0.89320734,  1.46075606],
       [-1.03903283,  0.81373347, -1.23896502, -1.0471685 ],
       [-0.40676133, -1.74371458,  0.1440657 ,  0.14079576],
       [ 0.22551017, -0.81373347,  0.77795478,  0.53678385],
       [-0.28030703, -0.58123819,  0.66270222,  1.06476797],
       [ 1.23714456, -0.11624764,  1.0084599 ,  1.196764  ],
       [-0.91257853,  1.5112193 , -1.2965913 , -1.0471685 ],
       [-1.16548713, -1.5112193 , -0.25931826, -0.25519232],
       [-0.65966993,  1.5112193 , -1.2965913 , -1.31116056],
       [-1.54485003,  0.34874292, -1.35421758, -1.31116056],
       [-0.02739843, -1.04622875,  0.1440657 ,  0.00879974],
       [-0.78612423, -0.81373347,  0.08643942,  0.27279179],
       [ 0.85778167, -0.11624764,  0.83558106,  1.06476797],
       [ 0.98423596, -0.11624764,  0.37457082,  0.27279179],
       [ 1.36359886,  0.11624764,  0.66270222,  0.40478782],
       [ 2.62814186,  1.74371458,  1.52709642,  1.06476797],
       [ 1.11069026, -1.27872403,  1.18133874,  0.80077591],
       [ 0.73132737, -0.58123819,  1.06608618,  1.196764  ],
       [-1.03903283, -0.11624764, -1.23896502, -1.31116056],
       [-0.15385273, -0.34874292,  0.25931826,  0.14079576],
       [-1.03903283, -2.44120041, -0.1440657 , -0.25519232],
       [-0.15385273, -0.11624764,  0.25931826,  0.00879974],
       [-1.03903283,  0.58123819, -1.35421758, -1.31116056],
       [-1.29194143,  0.11624764, -1.23896502, -1.31116056],
       [-0.40676133, -1.5112193 , -0.02881314, -0.25519232],
       [ 1.74296176,  0.34874292,  1.2965913 ,  0.80077591],
       [ 0.22551017, -1.97620986,  0.1440657 , -0.25519232],
       [-1.16548713, -1.27872403,  0.4321971 ,  0.66877988],
       [ 1.11069026, -0.11624764,  0.83558106,  1.46075606],
       [-0.78612423,  1.04622875, -1.2965913 , -1.31116056],
       [-0.91257853,  1.74371458, -1.23896502, -1.31116056],
       [ 0.60487307, -0.81373347,  0.66270222,  0.80077591],
       [ 0.35196447, -0.58123819,  0.1440657 ,  0.14079576],
       [ 1.36359886,  0.11624764,  0.95083362,  1.196764  ],
       [ 0.22551017,  0.81373347,  0.4321971 ,  0.53678385],
       [ 0.35196447, -0.11624764,  0.48982338,  0.27279179],
       [-0.15385273, -0.58123819,  0.4321971 ,  0.14079576],
       [-1.92421292, -0.11624764, -1.52709642, -1.44315659],
       [ 0.35196447, -0.58123819,  0.54744966,  0.00879974],
       [-1.67130433, -1.74371458, -1.41184386, -1.17916453],
       [-1.29194143, -0.11624764, -1.35421758, -1.44315659],
       [-0.02739843, -0.81373347,  0.77795478,  0.93277194],
       [ 1.36359886,  0.34874292,  1.12371246,  1.46075606],
       [-0.53321563,  0.81373347, -1.18133874, -1.31116056],
       [ 0.09905587, -0.11624764,  0.25931826,  0.40478782]])

In [7]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train_std, y_train)

KNeighborsClassifier(n_neighbors=3)

In [8]:
y_pred = knn_model.predict(X_test_std)
print(y_pred)
print(y_test)

[1 0 2 2 0 0 2 2 1 0 0 1 2 1 2 1 0 0 0 0 0 2 2 1 2 2 1 1 1 1]
[1 0 2 2 0 0 2 1 2 0 0 1 2 1 2 1 0 0 0 0 0 2 2 1 2 2 1 1 1 1]

In [9]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9333333333333333